kibot:
  version: 1

globals:
  # Filters for KiBot warnings
  filters:
    - filter: Ignore PcbDraw missing components
      number: 103
    - filter: Ignore missing KiCad config, not in docker images
      number: 8
    - filter: Ignore missing KiCad 3D models, not in docker images
      number: 10
    - filter: Ignore missing KiCad config from KiAuto, not in docker images
      number: 58
      regex: kicad_common.json
  # This will undo the `set_text_variables` when we run it locally
  restore_project: true
  # We will use a value externally formatted
  time_reformat: false

preflight:
  check_zone_fills: true
  run_erc: true
  run_drc: true
  # Filters for ERC/DRC errors/warnings
  filters:
    - filter: 'We know some connectors extend outside the board'
      error: 'silk_over_copper'
      regex: 'clipped by solder mask'
  set_text_variables:
    # The revision will be the short git hash
    # We use ${git_hash} for the REV field in the worksheet (frame)
    - name: 'git_hash'
      command: 'git log -1 --format="%h" $KIBOT_PCB_NAME'
      before: 'Git:'
    # Coherent date and time for the schematic and PCB
    # This will be the time stamp of the files generation, not the commit times
    # We use `${date}` for the time field in the worksheet (frame)
    - name: 'date'
      command: 'date --iso-8601=minutes'

outputs:
  - name: 'bom_xlsx'
    comment: "Spreadsheet for the Bill of Materials"
    type: bom
    dir: 'output/bom'
    options: &bom_options
      xlsx:
        datasheet_as_link: MFP
        title: 'KiBot example'
        max_col_width: 40
        highlight_empty: false
      columns:
        - Row
        - References
        - Value
        - Footprint
        - Hersteller
        - Nummer
        - Qty
      normalize_values: true

  - name: 'print_sch'
    comment: 'Schematic PDF'
    type: pdf_sch_print
    dir: 'output/schematic'
    #options:
      # Append the variant to the title
      #title: "+ (%V variant)"

  - name: 'gerbers'
    comment: 'Gerber Files'
    type: gerber
    dir: 'output/gerber'
    layers:
      - B.Cu
      - F.Silkscreen
      - F.Fab
      - Edge.Cuts
      - User.Drawings

  - name: drill
    comment: Drill files
    type: excellon
    dir: 'output/drill'
    options:
      map:
        type: pdf
      pth_and_npth_single_file: true

  - name: print_pdf
    comment: 'PCB PDF'
    type: pcb_print
    dir: 'output/pcb'
    options:
      force_edge_cuts: true
      keep_temporal_files: true
      # Append the variant to the title
      title: "+ (test)"
      # This is the worksheet we selected in the project, no need to specify it again
      # sheet_reference_layout: pcb_print.kicad_wks
      scaling: 2.0
      pages:
        - layers: [ B.Cu, F.Silkscreen, F.Fab, User.Drawings ]
          sheet: 'Fabrication layers'
        - layers:
            - layer: B.Cu
            - layer: F.Silkscreen
            - layer: F.Fab
            - layer: User.Drawings
          sheet: 'Top layer'
          mirror: true

  - name: board_top
    comment: "Top layer view"
    type: pcbdraw
    dir: 'output/pcb'
    options:
      format: jpg
      dpi: 300

  - name: board_top_filled
    comment: "Top layer view with components"
    type: pcbdraw
    dir: 'output/pcb'
    output_id: '-filled'
    options:
      format: jpg
      dpi: 300
      show_components: all

  - name: board_bottom
    comment: "Bottom layer view"
    type: pcbdraw
    dir: 'output/pcb'
    options:
      format: jpg
      dpi: 300
      bottom: true

  - name: board_bottom_filled
    comment: "Bottom layer view with components"
    type: pcbdraw
    dir: 'output/pcb'
    output_id: '-filled'
    options:
      format: jpg
      dpi: 300
      bottom: true
      show_components: all
      
  - name: 3D
    comment: "STEP 3D model"
    type: step
    dir: 'output/3D'

  - name: 3D_top_view
    comment: "3D render from top"
    type: render_3d
    dir: 'output/3D'
    options:
      zoom: 4
      rotate_x: 3
      rotate_z: 3
      ray_tracing: true

  - name: 3D_top_view_HQ
    comment: "3D render from top (High Quality)"
    type: blender_export
    dir: 'output/3D'
    options:
      render_options:
        transparent_background: true
        samples: 20
      point_of_view:
        rotate_x: 30
        rotate_z: -20
      outputs:
        - type: blender
        - type: render